---
- name: Clone the repository
  git:
    repo: '{{ cosmospruner_repo }}'
    dest: '/home/ubuntu/cosmos-pruner'
    version: main
    update: yes
    force: yes
    recursive: no

- name: Run make build
  command: 'make build'
  args:
    chdir: '/home/ubuntu/cosmos-pruner'
  environment:
    PATH: '{{ path }}'
    GOROOT: '/usr/local/go'
    GOPATH: '{{ user_dir }}/goApps'

- name: Change ownership
  file:
    path: '/home/ubuntu/cosmos-pruner'
    owner: ubuntu
    group: ubuntu
    recurse: yes
    state: directory

- name: Move the binary to /home/ubuntu/goApps/bin
  command: 'mv /home/ubuntu/cosmos-pruner/build/cosmos-pruner {{ user_dir }}/goApps/bin'